#!/usr/bin/env python

import actionlib
import copy
from geometry_msgs.msg import Pose
from intel_aero_navigation.msg import WaypointNavigationAction, WaypointNavigationGoal
from math import cos, sin, pi
import numpy as np
import rospy


def fetch_param_warn(name, default_value):
    try:
        value = rospy.get_param(name)
    except KeyError:
        rospy.logwarn('failed to fetch param \'%s\' from parameter server; using a default value of %s' % (name, str(default_value)))
        return default_value
    return value


def circle(rad, theta):
    pts = np.zeros((theta.size,2))
    pts[:,0] = rad*np.cos(theta)
    pts[:,1] = rad*np.sin(theta)
    return pts


def ellipse(a, b, phi, trans, theta):
    pts = np.zeros((theta.size,2))
    pts[:,0] =  a*cos(phi)*np.cos(theta) + b*sin(phi)*np.sin(theta) + trans[0]
    pts[:,1] = -a*sin(phi)*np.cos(theta) + b*cos(phi)*np.sin(theta) + trans[1]
    return pts


if __name__ == '__main__':

    quad_count = 3
    waypoint_count = 30
    desired_altitude = fetch_param_warn('/desired_altitude', 15.0)  # meters

    #
    # generate ellipse points
    #

    # ellipse parameters
    a = 14.0
    b = 17.5
    phi = 0.0
    trans = np.array((-60.0, -110.0))

    # elipse points
    ellipse_points = []
    for i in range(quad_count):
        theta = np.linspace(0.0, 2.0*pi, num=waypoint_count) + 2.0*pi*i/float(quad_count)
        ellipse_points += [ellipse(a, b, phi, trans, theta)]

    #
    # send goals to quads
    #

    try:
        rospy.init_node('lejeune_patrol_node')

        clients = []
        for i in range(quad_count):
            name = '/aero%d/vel_nav_nodelet' % (i+1)
            clients += [actionlib.SimpleActionClient(name, WaypointNavigationAction)]
            rospy.loginfo('waiting for %s to start' % (name))
            clients[i].wait_for_server()

        for i in range(quad_count):
            goal = WaypointNavigationGoal()
            goal.header.frame_id = 'world'
            goal.header.stamp = rospy.get_rostime()
            goal.end_action = WaypointNavigationGoal.LAND

            for j in range(waypoint_count):
                pose = Pose()
                pose.position.x = ellipse_points[i][j,0]
                pose.position.y = ellipse_points[i][j,1]
                pose.position.z = desired_altitude
                pose.orientation.w = 1.0

                goal.waypoints += [copy.deepcopy(pose)]

            clients[i].send_goal(goal)

        for i in range(quad_count):
            rospy.loginfo('waiting for aero%s to complete' % (i+1))
            clients[i].wait_for_result()

    except rospy.ROSInterruptException:
        pass
