#!/usr/bin/env python3


import rospy
from network_planner.network_planner import NetworkPlanner
from socp.msg import QoS


if __name__ == '__main__':
    try:
        node_name = 'connectivity_network_planner'
        rospy.init_node(node_name)

        run_planner = True
        if not rospy.has_param('/qos'):
            run_planner = False
            rospy.logfatal('[{}] failed to fetch ROS param \'qos\''.format(node_name))
        else:
            qos_param = rospy.get_param('/qos')

        if run_planner is True:
            qos = [QoS(q['margin'], q['confidence'], q['src'], q['dest']) for q in qos_param]

            network_planner = NetworkPlanner(qos)
            network_planner.run()

    except rospy.ROSInterruptException:
        pass
