# demo parameters
task_agent_ids:    [1, 2]
comm_agent_ids:    [3, 4, 5]
nuc1/desired_altitud:  3.0
nuc2/desired_altitud:  3.0
nuc3/desired_altitud:  5.0    # meters
nuc4/desired_altitud:  7.0    # meters
nuc5/desired_altitud:  9.0    # meters

# channel model
N0: -70.0  # -85.0  receiver noise (dBm)
n:    2.52 #   2.52 decay exponent
L0: -48.0  # -53.0  transmit power (dBm)
a:    0.2  #   0.2  variance sigmoid param 1
b:    0.6  #   0.6  variance sigmoid param 2

#Network Planner Parameters
connectivity_network_planner/collision_distance: 4.0
connectivity_network_planner/minimum_update_rate: 5
connectivity_network_planner/world_frame: world
connectivity_network_planner/planner_type: moving
connectivity_network_planner/print_routes: false
connectivity_network_planner/pose_topic: aero#/pose
connectivity_network_planner/nav_nodelet: /aero#/gazebo_vel_nav_nodelet
safety_x_min: 8
safety_x_max: 8
safety_y_min: 8
safety_y_max: 8

# communication requirements
qos:
  - margin: 0.15
    confidence: 0.75
    src: 1
    dest: [2]
  - margin: 0.15
    confidence: 0.75
    src: 2
    dest: [1]

# Way Points for Task Agents

aero1/gazebo_vel_nav_nodelet/desired_trajectory:
  - - 9.0
    - -9.0
    - 3.0
  - - 9.0
    - 9.0
    - 3.0
aero2/gazebo_vel_nav_nodelet/desired_trajectory:
  - - -9.0
    - 9.0
    - 3.0
  - - -9.0
    - -9.0
    - 3.0

