# demo parameters
task_agent_ids:    [1, 2, 3]
comm_agent_ids:    [4]
desired_altitude:  2.0    # meters

# channel model
N0: -70.0  # -85.0  receiver noise (dBm)
n:    2.52 #   2.52 decay exponent
L0: -48.0  # -53.0  transmit power (dBm)
a:    0.2  #   0.2  variance sigmoid param 1
b:    0.6  #   0.6  variance sigmoid param 2

# communication requirements
qos:
  - margin: 0.025
    confidence: 0.75
    src: 1
    dest: [2, 3]
  - margin: 0.025
    confidence: 0.75
    src: 2
    dest: [1, 3]
  - margin: 0.025
    confidence: 0.75
    src: 3
    dest: [1, 2]
