# demo parameters
task_agent_ids:    [1, 2, 3]
comm_agent_ids:    [4, 5, 6]
desired_altitude:  15.0 # meters

# channel model
N0: -70.0  # -85.0  receiver noise (dBm)
n:    2.52 #   2.52 decay exponent
L0: -48.0  # -53.0  transmit power (dBm)
a:    0.2  #   0.2  variance sigmoid param 1
b:    0.6  #   0.6  variance sigmoid param 2

# communication requirements
comm_reqs:
  - rate: 0.1
    qos: 0.75
    src: 1
    dest: 2
  - rate: 0.1
    qos: 0.75
    src: 1
    dest: 3
  - rate: 0.1
    qos: 0.75
    src: 2
    dest: 1
  - rate: 0.1
    qos: 0.75
    src: 2
    dest: 3
  - rate: 0.1
    qos: 0.75
    src: 3
    dest: 1
  - rate: 0.1
    qos: 0.75
    src: 3
    dest: 2
